name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: qiayuanl/legged_control2
          token: ${{ secrets.GH_PAT }}
          path: 'doc/legged_control2'
      - uses: actions/checkout@v4
        with:
          repository: qiayuanl/mujoco_sim_ros2
          path: 'doc/mujoco_sim_ros2'
          fetch-tags: true
      - uses: actions/checkout@v4
        with:
          repository: qiayuanl/mujoco_ros2_control
          token: ${{ secrets.GH_PAT }}
          path: 'doc/mujoco_ros2_control'
          ref: 'legged_control'
          fetch-tags: true
      - uses: actions/setup-python@v5
      - name: Install python dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser rosdoc2
      - name: Install doxygen and graphviz
        run: sudo apt-get install -y doxygen graphviz
      - name: Sphinx build
        run: |
          make html-with-api
      - name: rosdoc2 build
        run: |
          make rosdoc2
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
          force_orphan: true
